### PR TITLE
[WIP]: Adding detailed documentation with videos!

### PR DESCRIPTION
**Pull request by dblodorn**

### CODE REVIEW

**Comment by dblodorn** [comment]
Chapter 1:
https://www.loom.com/share/2c06e5556bc4416095491d5ecb595703

**Comment by dblodorn** [comment]
Chapter 2 - demo app usage and more repo exploration:
[https://www.loom.com/share/1bc4f356142046088f40fd02b804eb5d](https://www.loom.com/share/1bc4f356142046088f40fd02b804eb5d)

**Comment by dblodorn** [comment]
Chapter 3: Initializing a fresh package directory.
[https://www.loom.com/share/7a925693f28f4031a8588dd0483d7828](https://www.loom.com/share/7a925693f28f4031a8588dd0483d7828)

**Review by Valcoholics — APPROVED** [review]

**Comment by dblodorn** [comment]
Chapter 4: Importing and modifying your component in sample app:
[https://www.loom.com/share/775d05ae0e7e4a15baf941ce6b519f95](https://www.loom.com/share/775d05ae0e7e4a15baf941ce6b519f95)

**Comment by dblodorn** [comment]
Chapter 5: Publish step
[https://www.loom.com/share/c60acbc744f745abacf7aa1af0b467ab](https://www.loom.com/share/c60acbc744f745abacf7aa1af0b467ab)

**Comment by dblodorn** [comment]
Chapter 6: Finally we consume the package in another app:
[https://www.loom.com/share/92ef615552c9401d81f3b5f21702afe4](https://www.loom.com/share/92ef615552c9401d81f3b5f21702afe4)

**Comment by dblodorn** [comment]
@Valcoholics @salieflewis @losingmyego @0xTranqui @Javier-Szyfer 
FULL TUTORIAL HERE:
https://github.com/dblodorn/dains-really-fly-package

**Pull request merged**
